workflows:
  ios-workflow:
    name: iOS IPA Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Install CocoaPods
        script: |
          cd ios && pod install --repo-update
      - name: Build IPA
        script: |
          if [ -z "$CM_EXPORT_OPTIONS_PLIST" ]; then
            echo "Error: Code signing is not configured. Please go to Codemagic -> Project Settings -> iOS Code Signing and enable Automatic or Manual signing."
            exit 1
          fi
          xcode-project build-ipa \
            --workspace ios/CosmeticsApp.xcworkspace \
            --scheme CosmeticsApp \
            --export-options-plist "$CM_EXPORT_OPTIONS_PLIST"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - YOUR_EMAIL@EXAMPLE.COM
