workflows:
  ios-workflow:
    name: iOS IPA Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Install CocoaPods
        script: |
          cd ios && pod install --repo-update
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace ios/CosmeticsApp.xcworkspace \
            --scheme CosmeticsApp
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - YOUR_EMAIL@EXAMPLE.COM
